import unrealsdk
import random

from pathlib import Path
from unrealsdk.hooks import Type, Block
from unrealsdk.unreal import UObject, WrappedStruct, BoundFunction
from mods_base import hook, get_pc, SETTINGS_DIR, build_mod, ENGINE
from mods_base.options import BaseOption, BoolOption
from unrealsdk import logging, make_struct, find_class


def load_obj (definition:str, object:str):
    object_class = unrealsdk.find_class(definition)
    current_obj = ENGINE.DynamicLoadObject(object, object_class, False)
    return current_obj


Enemy_List =   ["gd_population_enemies.Bandits.Bandit_BaronFlynt",
                "gd_population_enemies.Bandits.Bandit_Bonehead",
                "gd_population_enemies.Bandits.Bandit_JaynisKobb",
                "gd_population_enemies.Bandits.Bandit_Krom",
                "gd_population_enemies.Bandits.Bandit_Ninetoes",
                "gd_population_enemies.Bandits.Bandit_OneEyeJack",
                "gd_population_enemies.Bandits.Bandit_Sledge",
                "gd_population_enemies.Bandits.Bandit_TaylorKobb",
                "gd_population_enemies.Bandits.BanditSquad_BadassBandits",
                "gd_population_enemies.Bandits.BanditSquad_BadassElite",
                "gd_population_enemies.Bandits.BanditSquad_BadassHeavy",
                "gd_population_enemies.Bandits.BanditSquad_BadassPsycho",
                "gd_population_enemies.Bandits.BanditSquad_Franz",
                "gd_population_enemies.Bandits.BanditSquad_Hanz",
                "gd_population_enemies.Bandits.BanditSquad_Insane",
                "gd_population_enemies.Bandits.BanditSquad_Intro",
                "gd_population_enemies.Bandits.BanditSquad_KingWeeWee",
                "gd_population_enemies.Bandits.BanditSquad_MidgetPsycho",
                "gd_population_enemies.Bandits.BanditSquad_MidgetShotgunner",
                "gd_population_enemies.Bandits.BanditSquad_Mixture",
                "gd_population_enemies.Bandits.BanditSquad_Psychos",
                "gd_population_enemies.Bandits.BanditSquad_Reaver",
                "gd_population_enemies.Bandits.BanditSquad_RoidRagePsycho",
                "gd_population_enemies.Bandits.Highwaymen_RangeMedium",
                "gd_population_enemies.Bloodwing.NorthernCommon_Wing",
                "gd_population_enemies.Bloodwing.RedTailed_Wing",
                "gd_population_enemies.Bloodwing.TrashFeeder",
                "gd_population_enemies.Bloodwing.YellowCrested_Wing",
                "gd_population_enemies.ChetaPaw.pop_enemy_vehicle_chetaPaw",
                "gd_population_enemies.ChetaPaw.pop_enemy_vehicle_ChetaPaw_driver",
                "gd_population_enemies.ChetaPaw.pop_enemy_vehicle_ChetaPaw_gunner",
                "gd_population_enemies.ChetaPaw.pop_enemy_vehicle_chetaPaw_Mad_Mel",
                "gd_population_enemies.CrabWorms.CrabWormSquad_Large",
                "gd_population_enemies.CrabWorms.CrabWormSquad_Small",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Badass",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Elite_Badass",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Heavy_Badass",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Master_McCloud",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Mixture",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Private_Badass",
                "gd_population_enemies.CrimsonLance.CrimsonLanceSquad_RoyalGuard",
                "gd_population_enemies.Guardians.Guardian_TheGhost",
                "gd_population_enemies.Guardians.Guardian_TheGhostBig",
                "gd_population_enemies.Guardians.GuardianArchSquad",
                "gd_population_enemies.Guardians.GuardianPrincArchSquad",
                "gd_population_enemies.Guardians.GuardianPrincipleBadass",
                "gd_population_enemies.Guardians.GuardianPrincipleSquad",
                "gd_population_enemies.Guardians.GuardianPrincSeraSquad",
                "gd_population_enemies.Guardians.GuardianSeraArchSquad",
                "gd_population_enemies.Guardians.GuardianSeraSquad",
                "gd_population_enemies.Guardians.GuardianSquad",
                "gd_population_enemies.Lancer.pop_enemy_vehicle_Lancer",
                "gd_population_enemies.Lancer.pop_enemy_vehicle_Lancer_driver",
                "gd_population_enemies.Lancer.pop_enemy_vehicle_Lancer_gunner",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_driver",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_gunner",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_melpatrol_mg",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_melpatrol_rocket",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_outrider",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_outrider_rocketeer",
                "gd_population_enemies.OutRider.pop_enemy_vehicle_sideclinger",
                "gd_population_enemies.Rakk.RakkSquad_BabyRakk",
                "gd_population_enemies.Rakk.RakkSquad_Bloated",
                "gd_population_enemies.Rakk.RakkSquad_Champions",
                "gd_population_enemies.Rakk.RakkSquad_Feeder",
                "gd_population_enemies.Rakk.RakkSquad_KamikazeRakk",
                "gd_population_enemies.Rakk.RakkSquad_Mothrakk",
                "gd_population_enemies.Rakk.RakkSquad_MothRakkBattle",
                "gd_population_enemies.Rakk.RakkSquad_Rakkinishu",
                "gd_population_enemies.Rakk.RakkSquad_Regular",
                "gd_population_enemies.RakkHive.PopDef_RakkHive",
                "gd_population_enemies.Scythids.ScythidSquad_Bleeder",
                "gd_population_enemies.Scythids.ScythidSquad_Champions",
                "gd_population_enemies.Scythids.ScythidSquad_Harmless",
                "gd_population_enemies.Scythids.ScythidSquad_Regular",
                "gd_population_enemies.Scythids.ScythidSquad_Regular_NoBadass",
                "gd_population_enemies.Scythids.ScythidSquad_Slither",
                "gd_population_enemies.Skags_SkagDen.AlphaSkagDen_Champion",
                "gd_population_enemies.Skags_SkagDen.AlphaSkagDen_Marley",
                "gd_population_enemies.Skags_SkagDen.AlphaSkagDen_Moe",
                "gd_population_enemies.Skags_SkagDen.AlphaSkagDen_Regular",
                "gd_population_enemies.Skags_SkagDen.AlphaSkagDen_Skagzilla",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Champions",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Digit",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Pinky",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Regular",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Scar",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Skrappy",
                "gd_population_enemies.Skags_SkagDen.SkagDen_Skrappygrownup",
                "gd_population_enemies.Spiderants.SpiderantSquad_Champions",
                "gd_population_enemies.Spiderants.SpiderantSquad_Corrosive",
                "gd_population_enemies.Spiderants.SpiderantSquad_Fire",
                "gd_population_enemies.Spiderants.SpiderantSquad_Helob",
                "gd_population_enemies.Spiderants.SpiderantSquad_KingAracobb",
                "gd_population_enemies.Spiderants.SpiderantSquad_Queen",
                "gd_population_enemies.Spiderants.SpiderantSquad_QueenTarantella",
                "gd_population_enemies.Spiderants.SpiderantSquad_Regular",
                "gd_population_enemies.Spiderants.SpiderantSquad_Shock",
                "gd_population_enemies.Spiderants.SpiderantSquad_Spiderantling",
                "gd_population_enemies.Spiderants.SpiderantSquad_Widowmaker",
                "gd_population_enemies.Turrets.AutoTurret_Gatling",
                "gd_population_enemies.Turrets.AutoTurret_Grenade",
                "gd_population_enemies.Turrets.AutoTurret_Rocket",
                "gd_population_enemies.Turrets.BanditTurret_Gatling",
                "gd_population_enemies.Turrets.BanditTurret_Gunner",
                "gd_population_enemies.Turrets.BanditTurret_Krom",
                "gd_population_enemies.Turrets.DELETEME_AutoTurret_MachineGun",
                "gd_population_enemies.Turrets.DELETEME_Turrets_RangeMedium_Few",
                "gd_population_enemies.Turrets.DELETEME_Turrets_RangeShort_Few",
                "gd_population_enemies.Villagers.Villager_RangeMedium",





                "dlc1_gd_population_enemies.Turrets.AutoTurret_Gatling_Friendly",
                "dlc1_gd_population_enemies.Turrets.AutoTurret_Gatling_FriendlyB",
                "dlc1_gd_population_enemies.Turrets.AutoTurret_Gatling_FriendlyC",
                "dlc1_gd_population_enemies.Bloodwing.BloodWingSquad_CorpseEater",
                "dlc1_gd_population_enemies.Franken.FrankenBadass",
                "dlc1_gd_population_enemies.Franken.FrankenBill",
                "dlc1_gd_population_enemies.Franken.FrankenTank",
                "dlc1_gd_population_enemies.Franken.LootGoon",
                "dlc1_gd_population_enemies.Ned.NedEnemy",
                "dlc1_gd_population_enemies.Golem.Pumpkinhead",
                "dlc1_gd_population_enemies.Rakk.RakkSquad_UndeadRakk",
                "dlc1_gd_population_enemies.Ned.UndeadNed",
                "dlc1_gd_population_enemies.WereSkag.WereSkagSquad_Bigfoot",
                "dlc1_gd_population_enemies.WereSkag.WereSkagSquad_FatherOCallahan",
                "dlc1_gd_population_enemies.WereSkag.WereSkagSquad_HankReiss",
                "dlc1_gd_population_enemies.WereSkag.WereSkagSquad_RedJack",
                "dlc1_gd_population_enemies.WereSkag.WereSkagSquad_WereSkag",
                "dlc1_gd_population_enemies.WereSkag.WereSkagSquad_WhiskeyWesley",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_LanceZombies",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_MidgetZombies",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_Mixture",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_PsychoZombie",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_SlowZombies",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_SlowZombiesG",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_SpitZombie",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_SuicideZombie",
                "dlc1_gd_population_enemies.Zombies.ZombieSquad_TorsoZombie",






                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_BaronFlynt",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_Bonehead",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_Krom",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_Ninetoes",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_OneEyeJack",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_Sledge",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_Bandit_TaylorKobb",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_BanditSquad_Franz",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_BanditSquad_Hanz",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_BanditSquad_KingWeeWee",
                "dlc2_gd_population_enemies.Bandits_Wave5.dlc2_BanditSquad_Reaver",
                "dlc2_gd_population_enemies.Crimson_Wave5.dlc2_CrimsonLance_Master_McCloud",
                "dlc2_gd_population_enemies.Crimson_Wave5.dlc2_CrimsonLance_RoyalGuard",
                "dlc2_gd_population_enemies.Skags.dlc2_SkagDen_Digit",
                "dlc2_gd_population_enemies.Skags.dlc2_SkagDen_Pinky",
                "dlc2_gd_population_enemies.Spiderants.SpiderantSquad_Regular",
                "dlc2_gd_population_enemies.Bandits.Wave1_FirstWave_Bandits",
                "dlc2_gd_population_enemies.Scythids.Wave1_Starter_Scythid",
                "dlc2_gd_population_enemies.Skags.Wave1_Starter_Skags",
                "dlc2_gd_population_enemies.Spiderants.Wave1_Starter_Spiderants",
                "dlc2_gd_population_enemies.Bandits.Wave2_BanditSquad",
                "dlc2_gd_population_enemies.CrimsonLance.Wave2_CrimsonLance",
                "dlc2_gd_population_enemies.Guardians.Wave3_Horde_Guardians",
                "dlc2_gd_population_enemies.Bandits.Wave3_Horde_Psychos",
                "dlc2_gd_population_enemies.Spiderants.Wave3_Horde_Spiderants",
                "dlc2_gd_population_enemies.Guardians.Wave4_Badass_Guardians",
                "dlc2_gd_population_enemies.Scythids.Wave4_Badass_Scythid",
                "dlc2_gd_population_enemies.Skags.Wave4_Badass_Skags",
                "dlc2_gd_population_enemies.Spiderants.Wave4_Badass_Spiderants",
                "dlc2_gd_population_enemies.Bandits.Wave4_BadassWave_Bandits",
                "dlc2_gd_population_enemies.CrimsonLance.Wave4_CrimsonLance",






                "dlc3_gd_population_enemies.Skags.AlphaSkagDen_Regular",
                "dlc3_gd_population_enemies.Turrets.AutoTurret_Gatling",
                "dlc3_gd_population_enemies.Turrets.AutoTurret_Gatling_humans",
                "dlc3_gd_population_enemies.Turrets.AutoTurret_Grenade",
                "dlc3_gd_population_enemies.Turrets.AutoTurret_Rocket",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_BadassBandits",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_BadassElite",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_BadassHeavy",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_BadassPsycho",
                "dlc3_gd_population_enemies.Prisoners.BanditSquad_BadassThug",
                "dlc3_gd_population_enemies.Prisoners.BanditSquad_Banger",
                "dlc3_gd_population_enemies.Prisoners.Named.BanditSquad_Chaz",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Elite",
                "dlc3_gd_population_enemies.Prisoners.BanditSquad_Enforcer",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Grunt1",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Grunt2",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Heavy",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Insane",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Mixture",
                "dlc3_gd_population_enemies.Bandits.Named.BanditSquad_MotorHead",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Psycho",
                "dlc3_gd_population_enemies.Bandits.BanditSquad_Psychos",
                "dlc3_gd_population_enemies.Prisoners.BanditSquad_Punk",
                "dlc3_gd_population_enemies.Prisoners.Named.BanditSquad_Shank",
                "dlc3_gd_population_enemies.CrabWorms.CrabWormSquad_Armored",
                "dlc3_gd_population_enemies.CrabWorms.CrabwormSquad_CraweraxMixture",
                "dlc3_gd_population_enemies.CrabWorms.CrabwormSquad_CrawMaggot",
                "dlc3_gd_population_enemies.CrabWorms.CrabWormSquad_Small",
                "dlc3_gd_population_enemies.CrabWorms.CrabwormSquad_Unbeatable",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Ajax",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Assassin",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Assassin_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Assassin_Named1",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Assassin_Named2",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Assassin_Named3",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Assassin_Named4",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Assassin_Named5",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Badass_Armor",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_BadassDevastator",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_BadassRocketeer",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Corrosive",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Corrosive_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_CorrosiveMix",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Devastator",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Elite",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Elite_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Fire",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Fire_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_FireMix",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Heavy",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Heavy_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Knoxx",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Kyros",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Master_McCloud",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Medic",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Mixture",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Private",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Private_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Probe",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Rocketeer",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_RoyalGuard",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Shock",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_Shock_Badass",
                "dlc3_gd_population_enemies.CrimsonLance.CrimsonLanceSquad_ShockMix",
                "dlc3_gd_population_enemies.CrimsonLance.Named.CrimsonLanceSquad_Typhon",
                "dlc3_gd_population_enemies.Drifters.DrifterSquad_BadassDrifter",
                "dlc3_gd_population_enemies.Drifters.DrifterSquad_Drifter",
                "dlc3_gd_population_enemies.Drifters.Named.DrifterSquad_Named1",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_Badass",
                "dlc3_gd_population_enemies.Midgets.Named.MidgetSquad_DumpsterDiver",
                "dlc3_gd_population_enemies.Midgets.Named.MidgetSquad_MeatPop",
                "dlc3_gd_population_enemies.Midgets.Named.MidgetSquad_MidgetLance",
                "dlc3_gd_population_enemies.Midgets.Named.MidgetSquad_MiniSteve",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_Mixture",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_Raider",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_Ravager",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_Rustler",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_Shotgunner",
                "dlc3_gd_population_enemies.Midgets.Named.MidgetSquad_TWrestler",
                "dlc3_gd_population_enemies.Midgets.MidgetSquad_TWrestler",
                "dlc3_gd_population_enemies.Prisoners.PrisonSquad_Mixture",
                "dlc3_gd_population_enemies.SkagRiders.SkagRiderSquad_3Riders",
                "dlc3_gd_population_enemies.SkagRiders.SkagRiderSquad_Axe",
                "dlc3_gd_population_enemies.SkagRiders.SkagRiderSquad_Badass",
                "dlc3_gd_population_enemies.SkagRiders.SkagRiderSquad_Grenade",
                "dlc3_gd_population_enemies.SkagRiders.SkagRiderSquad_Mixture",
                "dlc3_gd_population_enemies.SkagRiders.SkagRiderSquad_Sword",








                "dlc4_gd_Population_Enemies.Skags_SkagDen.AlphaSkag-trapDen_Champion",
                "dlc4_gd_Population_Enemies.Skags_SkagDen.AlphaSkag-trapDen_Regular",
                "dlc4_gd_Population_Enemies.Turrets.AutoTurret_GatlingTrap",
                "dlc4_gd_Population_Enemies.Turrets.AutoTurret_GrenadeTrap",
                "dlc4_gd_Population_Enemies.Turrets.AutoTurret_Rocket_Player_Friendly",
                "dlc4_gd_Population_Enemies.Turrets.AutoTurret_RocketTrap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-eliteTrap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-HeavyTrap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-Trap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-Trap_Psychos",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-TrapSquad_BadassBandits-Trap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-TrapSquad_BadassHeavy-Trap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-TrapSquad_BadassPsycho-Trap",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-TrapSquad_Mixture",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.Bandit-TrapSquad_Psychos",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_BadassBandits",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_BadassHeavy",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_BadassPsycho",
                "dlc4_gd_Population_Enemies.Bandits.Named.BanditSquad_D-Bandits",
                "dlc4_gd_Population_Enemies.Bandits.Named.BanditSquad_D-Fault",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.BanditSquad_Midget-TrapShotgunner",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_MidgetPsycho",
                "dlc4_gd_Population_Enemies.Bandits.Bandit-Trap.BanditSquad_MidgetPsycho-Trap",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_MidgetShotgunner",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_Mixture",
                "dlc4_gd_Population_Enemies.Bandits.BanditSquad_Psychos",
                "dlc4_gd_Population_Enemies.Crab-Trap.Crab-TrapSquad_Large",
                "dlc4_gd_Population_Enemies.Crab-Trap.Crab-TrapSquad_Small",
                "dlc4_gd_Population_Enemies.Hyperion.Hyperion-TrapSquad",
                "dlc4_gd_Population_Enemies.Hyperion.HyperionFriendlySquad",
                "dlc4_gd_Population_Enemies.Hyperion.HyperionGuardTrapBadass",
                "dlc4_gd_Population_Enemies.Hyperion.HyperionSoldierTrapBadass",
                "dlc4_gd_Population_Enemies.Hyperion.HyperionSquad",
                "dlc4_gd_Population_Enemies.Hyperion.HyperionSuperbadass",
                "dlc4_gd_Population_Enemies.Hyperion.Hyperiontech",
                "dlc4_gd_Population_Enemies.Hyperion.HyperionTechTrapBadass",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_FirstA",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_FirstB",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_FirstGroup",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_Group",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_MeleeGroup",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_RangedA",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Claptrap_RangedB",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_ClaptrapK_First",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_ClaptrapKamakazee",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_ClaptrapMeleeBoxer",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_ClaptrapMeleeClub",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_ClaptrapMeleePunk",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_Clucktrap",
                "dlc4_gd_Population_Enemies.ClapTrap.PopDef_DLC4_INAC",
                "dlc4_gd_Population_Enemies.Test.PopDef_DLC4_Kamikaze",
                "dlc4_gd_Population_Enemies.Test.PopDef_DLC4_midget_Claptrap_Intro",
                "dlc4_gd_Population_Enemies.MINAC.PopDef_DLC4_MINAC_Eye",
                "dlc4_gd_Population_Enemies.MINAC.PopDef_DLC4_MINAC_EyeTurret",
                "dlc4_gd_Population_Enemies.MINAC.PopDef_DLC4_MINAC_Gatling",
                "dlc4_gd_Population_Enemies.MINAC.PopDef_DLC4_MINAC_Missile",
                "dlc4_gd_Population_Enemies.KnoxxTrap.PopDef_KnoxxTrap",
                "dlc4_gd_Population_Enemies.KnoxxTrap.PopDef_KnoxxTrap2",
                "dlc4_gd_Population_Enemies.NedTrap.PopDef_NedTrap",
                "dlc4_gd_Population_Enemies.RakkTrapHive.PopDef_RakkTrapHive",
                "dlc4_gd_Population_Enemies.SteeleTrap.PopDef_SteeleTrap",
                "dlc4_gd_Population_Enemies.SteeleTrap.PopDef_SteeleTrap2",
                "dlc4_gd_Population_Enemies.NedTrap.PopDef_UndeadNedTrap",
                "dlc4_gd_Population_Enemies.Rakk.Rakk-trapSquad_Bloated",
                "dlc4_gd_Population_Enemies.Rakk.Rakk-trapSquad_Champions",
                "dlc4_gd_Population_Enemies.Rakk.Rakk-trapSquad_Feeder",
                "dlc4_gd_Population_Enemies.Rakk.Rakk-trapSquad_KamikazeRakk-trap",
                "dlc4_gd_Population_Enemies.Rakk.Rakk-trapSquad_Regular",
                "dlc4_gd_Population_Enemies.Rakk.RakkSquad_BabyRakk-trap",
                "dlc4_gd_Population_Enemies.Skags_SkagDen.Skag-trapDen_Champions",
                "dlc4_gd_Population_Enemies.Skags_SkagDen.Skag-trapDen_Regular",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Champions",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Corrosive",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Fire",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Queen",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Regular",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Shock",
                "dlc4_gd_Population_Enemies.Spiderants.Spiderant-TrapSquad_Spiderantling"]



def randomize_enemies():
    global Enemy_List

    count = 0
    for x in unrealsdk.find_all("PopulationOpportunityDen"):
        count = count + 1
        if count > 1:
            popdef = Enemy_List[random.randint(0, len(Enemy_List) - 1)]
            x.PopulationDef = load_obj("PopulationDefinition",popdef)
    
    
    count = 0
    for x in unrealsdk.find_all("PopulationEncounter"):
        count = count + 1
        if count > 1:
            popdef = Enemy_List[random.randint(0, len(Enemy_List) - 1)]
            x.EncounterPopulationDef = load_obj("PopulationDefinition",popdef)